'''
How Do You Handle Exceptions With Try/Except/Finally In Python?
Explain with coding snippets. 


Example: Exception Handling Using try...
To handle the exception, we have put the code,
result = numerator/denominator inside the try block. 
Now when an exception occurs, the rest of the code inside the try block is skipped.
 The except block catches the exception and statements inside the except block are executed.

'''